// Auto-generated from Supabase schema. Do not edit by hand.
// Regenerate with: SUPABASE_DB_URL=... node scripts/gen-types.mjs

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      _schema_migrations: {
        Row: {
          filename: string;
          applied_at: string;
          sha256: string | null;
        };
        Insert: {
          filename: string;
          applied_at?: string;
          sha256?: string | null;
        };
        Update: {
          filename?: string;
          applied_at?: string;
          sha256?: string | null;
        };
        Relationships: [];
      };
      alerts: {
        Row: {
          id: string;
          kind: string;
          severity: string;
          title: string;
          detail: string | null;
          target_url: string | null;
          target_ref: string | null;
          resolved: boolean;
          resolved_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          kind: string;
          severity?: string;
          title: string;
          detail?: string | null;
          target_url?: string | null;
          target_ref?: string | null;
          resolved?: boolean;
          resolved_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          kind?: string;
          severity?: string;
          title?: string;
          detail?: string | null;
          target_url?: string | null;
          target_ref?: string | null;
          resolved?: boolean;
          resolved_at?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      ateliers: {
        Row: {
          id: string;
          name: string;
          contact_name: string | null;
          phone: string | null;
          email: string | null;
          address: string | null;
          city: string | null;
          postal_code: string | null;
          country: string;
          internal: boolean;
          specialties: string[];
          capacity: string | null;
          active: boolean;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          contact_name?: string | null;
          phone?: string | null;
          email?: string | null;
          address?: string | null;
          city?: string | null;
          postal_code?: string | null;
          country?: string;
          internal?: boolean;
          specialties?: string[];
          capacity?: string | null;
          active?: boolean;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          contact_name?: string | null;
          phone?: string | null;
          email?: string | null;
          address?: string | null;
          city?: string | null;
          postal_code?: string | null;
          country?: string;
          internal?: boolean;
          specialties?: string[];
          capacity?: string | null;
          active?: boolean;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      atmolead_config: {
        Row: {
          id: boolean;
          target_url: string;
          cron_expression: string;
          enabled: boolean;
          css_selectors: Json;
          last_run_at: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: boolean;
          target_url?: string;
          cron_expression?: string;
          enabled?: boolean;
          css_selectors?: Json;
          last_run_at?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: boolean;
          target_url?: string;
          cron_expression?: string;
          enabled?: boolean;
          css_selectors?: Json;
          last_run_at?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      atmolead_executions: {
        Row: {
          id: string;
          status: Database["public"]["Enums"]["atmolead_execution_status"];
          triggered_by: Database["public"]["Enums"]["atmolead_trigger"];
          started_at: string;
          finished_at: string | null;
          duration_ms: number | null;
          leads_found: number;
          leads_inserted: number;
          leads_skipped: number;
          error_message: string | null;
          worker_version: string | null;
          logs: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          status?: Database["public"]["Enums"]["atmolead_execution_status"];
          triggered_by: Database["public"]["Enums"]["atmolead_trigger"];
          started_at?: string;
          finished_at?: string | null;
          duration_ms?: number | null;
          leads_found?: number;
          leads_inserted?: number;
          leads_skipped?: number;
          error_message?: string | null;
          worker_version?: string | null;
          logs?: Json | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          status?: Database["public"]["Enums"]["atmolead_execution_status"];
          triggered_by?: Database["public"]["Enums"]["atmolead_trigger"];
          started_at?: string;
          finished_at?: string | null;
          duration_ms?: number | null;
          leads_found?: number;
          leads_inserted?: number;
          leads_skipped?: number;
          error_message?: string | null;
          worker_version?: string | null;
          logs?: Json | null;
          created_at?: string;
        };
        Relationships: [];
      };
      atmolead_jobs: {
        Row: {
          id: string;
          status: Database["public"]["Enums"]["atmolead_job_status"];
          triggered_by: Database["public"]["Enums"]["atmolead_trigger"];
          scheduled_at: string;
          picked_at: string | null;
          finished_at: string | null;
          execution_id: string | null;
          requested_by: string | null;
          payload: Json | null;
          error_message: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          status?: Database["public"]["Enums"]["atmolead_job_status"];
          triggered_by: Database["public"]["Enums"]["atmolead_trigger"];
          scheduled_at?: string;
          picked_at?: string | null;
          finished_at?: string | null;
          execution_id?: string | null;
          requested_by?: string | null;
          payload?: Json | null;
          error_message?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          status?: Database["public"]["Enums"]["atmolead_job_status"];
          triggered_by?: Database["public"]["Enums"]["atmolead_trigger"];
          scheduled_at?: string;
          picked_at?: string | null;
          finished_at?: string | null;
          execution_id?: string | null;
          requested_by?: string | null;
          payload?: Json | null;
          error_message?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      atmolead_leads_raw: {
        Row: {
          id: string;
          execution_id: string | null;
          external_ref: string | null;
          raw_data: Json;
          source_url: string | null;
          client_id: string | null;
          lm_lead_id: string | null;
          inserted: boolean;
          skip_reason: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          execution_id?: string | null;
          external_ref?: string | null;
          raw_data: Json;
          source_url?: string | null;
          client_id?: string | null;
          lm_lead_id?: string | null;
          inserted?: boolean;
          skip_reason?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          execution_id?: string | null;
          external_ref?: string | null;
          raw_data?: Json;
          source_url?: string | null;
          client_id?: string | null;
          lm_lead_id?: string | null;
          inserted?: boolean;
          skip_reason?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      audit_log: {
        Row: {
          id: string;
          actor_id: string | null;
          action: string;
          entity_type: string;
          entity_id: string | null;
          meta: Json;
          ip_address: string | null;
          user_agent: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          actor_id?: string | null;
          action: string;
          entity_type: string;
          entity_id?: string | null;
          meta?: Json;
          ip_address?: string | null;
          user_agent?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          actor_id?: string | null;
          action?: string;
          entity_type?: string;
          entity_id?: string | null;
          meta?: Json;
          ip_address?: string | null;
          user_agent?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      automation_rules: {
        Row: {
          id: string;
          event_key: string;
          label: string;
          description: string | null;
          module: string | null;
          sms_enabled: boolean;
          sms_template_key: string | null;
          email_enabled: boolean;
          email_template_key: string | null;
          updated_at: string;
        };
        Insert: {
          id?: string;
          event_key: string;
          label: string;
          description?: string | null;
          module?: string | null;
          sms_enabled?: boolean;
          sms_template_key?: string | null;
          email_enabled?: boolean;
          email_template_key?: string | null;
          updated_at?: string;
        };
        Update: {
          id?: string;
          event_key?: string;
          label?: string;
          description?: string | null;
          module?: string | null;
          sms_enabled?: boolean;
          sms_template_key?: string | null;
          email_enabled?: boolean;
          email_template_key?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      bc_lines: {
        Row: {
          id: string;
          bc_id: string;
          dossier_item_id: string | null;
          position: number;
          ref: string | null;
          label: string;
          qty: number;
          unit_label: string;
          unit_price_ht: number;
          total_ht: number | null;
        };
        Insert: {
          id?: string;
          bc_id: string;
          dossier_item_id?: string | null;
          position?: number;
          ref?: string | null;
          label: string;
          qty?: number;
          unit_label?: string;
          unit_price_ht?: number;
          total_ht?: number | null;
        };
        Update: {
          id?: string;
          bc_id?: string;
          dossier_item_id?: string | null;
          position?: number;
          ref?: string | null;
          label?: string;
          qty?: number;
          unit_label?: string;
          unit_price_ht?: number;
          total_ht?: number | null;
        };
        Relationships: [];
      };
      bons_commande: {
        Row: {
          id: string;
          number: string;
          supplier_id: string;
          dossier_id: string | null;
          status: Database["public"]["Enums"]["bc_status"];
          amount_ht: number;
          language: Database["public"]["Enums"]["lang"];
          expected_at: string | null;
          received_at: string | null;
          pdf_url: string | null;
          sent_at: string | null;
          notes: string | null;
          franco_override: boolean;
          created_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          number: string;
          supplier_id: string;
          dossier_id?: string | null;
          status?: Database["public"]["Enums"]["bc_status"];
          amount_ht?: number;
          language?: Database["public"]["Enums"]["lang"];
          expected_at?: string | null;
          received_at?: string | null;
          pdf_url?: string | null;
          sent_at?: string | null;
          notes?: string | null;
          franco_override?: boolean;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          number?: string;
          supplier_id?: string;
          dossier_id?: string | null;
          status?: Database["public"]["Enums"]["bc_status"];
          amount_ht?: number;
          language?: Database["public"]["Enums"]["lang"];
          expected_at?: string | null;
          received_at?: string | null;
          pdf_url?: string | null;
          sent_at?: string | null;
          notes?: string | null;
          franco_override?: boolean;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      caisse_closures: {
        Row: {
          id: string;
          date: string;
          total_especes: number;
          total_cb: number;
          total_cheque: number;
          total_virement: number;
          cash_counted: number | null;
          variance: number | null;
          closed_by: string | null;
          closed_at: string | null;
          exported_to_pennylane: boolean;
          notes: string | null;
        };
        Insert: {
          id?: string;
          date: string;
          total_especes?: number;
          total_cb?: number;
          total_cheque?: number;
          total_virement?: number;
          cash_counted?: number | null;
          variance?: number | null;
          closed_by?: string | null;
          closed_at?: string | null;
          exported_to_pennylane?: boolean;
          notes?: string | null;
        };
        Update: {
          id?: string;
          date?: string;
          total_especes?: number;
          total_cb?: number;
          total_cheque?: number;
          total_virement?: number;
          cash_counted?: number | null;
          variance?: number | null;
          closed_by?: string | null;
          closed_at?: string | null;
          exported_to_pennylane?: boolean;
          notes?: string | null;
        };
        Relationships: [];
      };
      caisse_ticket_lines: {
        Row: {
          id: string;
          ticket_id: string;
          catalog_product_id: string | null;
          ref: string | null;
          label: string;
          qty: number;
          unit_label: string;
          unit_price_ht: number;
          total_ht: number | null;
          position: number;
        };
        Insert: {
          id?: string;
          ticket_id: string;
          catalog_product_id?: string | null;
          ref?: string | null;
          label: string;
          qty?: number;
          unit_label?: string;
          unit_price_ht: number;
          total_ht?: number | null;
          position?: number;
        };
        Update: {
          id?: string;
          ticket_id?: string;
          catalog_product_id?: string | null;
          ref?: string | null;
          label?: string;
          qty?: number;
          unit_label?: string;
          unit_price_ht?: number;
          total_ht?: number | null;
          position?: number;
        };
        Relationships: [];
      };
      caisse_tickets: {
        Row: {
          id: string;
          number: string;
          client_id: string | null;
          cashier_id: string | null;
          total_ht: number;
          total_ttc: number;
          discount_pct: number;
          payment_method: Database["public"]["Enums"]["payment_method"];
          paid_amount: number;
          cash_received: number | null;
          change_due: number | null;
          receipt_email: string | null;
          closure_id: string | null;
          created_at: string;
          pennylane_exported_at: string | null;
          pennylane_invoice_id: string | null;
          pennylane_export_notes: string | null;
          store_id: string | null;
        };
        Insert: {
          id?: string;
          number: string;
          client_id?: string | null;
          cashier_id?: string | null;
          total_ht?: number;
          total_ttc?: number;
          discount_pct?: number;
          payment_method: Database["public"]["Enums"]["payment_method"];
          paid_amount: number;
          cash_received?: number | null;
          change_due?: number | null;
          receipt_email?: string | null;
          closure_id?: string | null;
          created_at?: string;
          pennylane_exported_at?: string | null;
          pennylane_invoice_id?: string | null;
          pennylane_export_notes?: string | null;
          store_id?: string | null;
        };
        Update: {
          id?: string;
          number?: string;
          client_id?: string | null;
          cashier_id?: string | null;
          total_ht?: number;
          total_ttc?: number;
          discount_pct?: number;
          payment_method?: Database["public"]["Enums"]["payment_method"];
          paid_amount?: number;
          cash_received?: number | null;
          change_due?: number | null;
          receipt_email?: string | null;
          closure_id?: string | null;
          created_at?: string;
          pennylane_exported_at?: string | null;
          pennylane_invoice_id?: string | null;
          pennylane_export_notes?: string | null;
          store_id?: string | null;
        };
        Relationships: [];
      };
      catalog_products: {
        Row: {
          id: string;
          ref: string;
          name: string;
          category: string;
          description: string | null;
          unit_price_ht: number;
          unit_label: string;
          width_cm: number | null;
          raccord_cm: number | null;
          is_collection: boolean;
          stock_poland: number;
          stock_ukraine: number;
          active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          ref: string;
          name: string;
          category: string;
          description?: string | null;
          unit_price_ht: number;
          unit_label?: string;
          width_cm?: number | null;
          raccord_cm?: number | null;
          is_collection?: boolean;
          stock_poland?: number;
          stock_ukraine?: number;
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          ref?: string;
          name?: string;
          category?: string;
          description?: string | null;
          unit_price_ht?: number;
          unit_label?: string;
          width_cm?: number | null;
          raccord_cm?: number | null;
          is_collection?: boolean;
          stock_poland?: number;
          stock_ukraine?: number;
          active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      clients: {
        Row: {
          id: string;
          display_name: string;
          email: string | null;
          phone: string | null;
          address_pose: string | null;
          city: string | null;
          postal_code: string | null;
          channel: Database["public"]["Enums"]["channel"];
          source_notes: string | null;
          internal_notes: string | null;
          preferences: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
          source_id: string | null;
          store_id: string | null;
        };
        Insert: {
          id?: string;
          display_name: string;
          email?: string | null;
          phone?: string | null;
          address_pose?: string | null;
          city?: string | null;
          postal_code?: string | null;
          channel?: Database["public"]["Enums"]["channel"];
          source_notes?: string | null;
          internal_notes?: string | null;
          preferences?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          source_id?: string | null;
          store_id?: string | null;
        };
        Update: {
          id?: string;
          display_name?: string;
          email?: string | null;
          phone?: string | null;
          address_pose?: string | null;
          city?: string | null;
          postal_code?: string | null;
          channel?: Database["public"]["Enums"]["channel"];
          source_notes?: string | null;
          internal_notes?: string | null;
          preferences?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          source_id?: string | null;
          store_id?: string | null;
        };
        Relationships: [];
      };
      couturieres: {
        Row: {
          id: string;
          profile_id: string | null;
          name: string;
          internal: boolean;
          specialties: string[];
          active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          profile_id?: string | null;
          name: string;
          internal?: boolean;
          specialties?: string[];
          active?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          profile_id?: string | null;
          name?: string;
          internal?: boolean;
          specialties?: string[];
          active?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      devis: {
        Row: {
          id: string;
          number: string;
          version: number;
          client_id: string;
          channel: Database["public"]["Enums"]["channel"];
          status: Database["public"]["Enums"]["devis_status"];
          product_summary: string;
          product_detail: string | null;
          qty: number;
          total_ht: number;
          total_ttc: number;
          tva_rate: number;
          acompte_ht: number | null;
          acompte_ttc: number | null;
          acompte_pct: number;
          hide_measurements_for_client: boolean;
          client_viewed_at: string | null;
          pdf_url: string | null;
          workshop_notes: string | null;
          commercial_id: string | null;
          sent_at: string | null;
          valid_until: string | null;
          created_at: string;
          updated_at: string;
          client_access_token: string;
          source_id: string | null;
          store_id: string | null;
        };
        Insert: {
          id?: string;
          number: string;
          version?: number;
          client_id: string;
          channel: Database["public"]["Enums"]["channel"];
          status?: Database["public"]["Enums"]["devis_status"];
          product_summary: string;
          product_detail?: string | null;
          qty?: number;
          total_ht?: number;
          total_ttc?: number;
          tva_rate?: number;
          acompte_ht?: number | null;
          acompte_ttc?: number | null;
          acompte_pct?: number;
          hide_measurements_for_client?: boolean;
          client_viewed_at?: string | null;
          pdf_url?: string | null;
          workshop_notes?: string | null;
          commercial_id?: string | null;
          sent_at?: string | null;
          valid_until?: string | null;
          created_at?: string;
          updated_at?: string;
          client_access_token?: string;
          source_id?: string | null;
          store_id?: string | null;
        };
        Update: {
          id?: string;
          number?: string;
          version?: number;
          client_id?: string;
          channel?: Database["public"]["Enums"]["channel"];
          status?: Database["public"]["Enums"]["devis_status"];
          product_summary?: string;
          product_detail?: string | null;
          qty?: number;
          total_ht?: number;
          total_ttc?: number;
          tva_rate?: number;
          acompte_ht?: number | null;
          acompte_ttc?: number | null;
          acompte_pct?: number;
          hide_measurements_for_client?: boolean;
          client_viewed_at?: string | null;
          pdf_url?: string | null;
          workshop_notes?: string | null;
          commercial_id?: string | null;
          sent_at?: string | null;
          valid_until?: string | null;
          created_at?: string;
          updated_at?: string;
          client_access_token?: string;
          source_id?: string | null;
          store_id?: string | null;
        };
        Relationships: [];
      };
      devis_lines: {
        Row: {
          id: string;
          devis_id: string;
          position: number;
          ref: string | null;
          label: string;
          detail: string | null;
          qty: number;
          unit_label: string;
          unit_price_ht: number;
          total_ht: number | null;
          catalog_product_id: string | null;
          meta: Json;
        };
        Insert: {
          id?: string;
          devis_id: string;
          position?: number;
          ref?: string | null;
          label: string;
          detail?: string | null;
          qty?: number;
          unit_label?: string;
          unit_price_ht: number;
          total_ht?: number | null;
          catalog_product_id?: string | null;
          meta?: Json;
        };
        Update: {
          id?: string;
          devis_id?: string;
          position?: number;
          ref?: string | null;
          label?: string;
          detail?: string | null;
          qty?: number;
          unit_label?: string;
          unit_price_ht?: number;
          total_ht?: number | null;
          catalog_product_id?: string | null;
          meta?: Json;
        };
        Relationships: [];
      };
      devis_versions: {
        Row: {
          id: string;
          devis_id: string;
          version: number;
          total_ttc: number;
          snapshot: Json;
          pdf_url: string | null;
          notes: string | null;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          devis_id: string;
          version: number;
          total_ttc: number;
          snapshot: Json;
          pdf_url?: string | null;
          notes?: string | null;
          created_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          devis_id?: string;
          version?: number;
          total_ttc?: number;
          snapshot?: Json;
          pdf_url?: string | null;
          notes?: string | null;
          created_by?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      dossier_items: {
        Row: {
          id: string;
          dossier_id: string;
          type: Database["public"]["Enums"]["dossier_item_type"];
          label: string;
          ref: string | null;
          supplier_id: string | null;
          couturiere_id: string | null;
          status: Database["public"]["Enums"]["dossier_item_status"];
          qr_code: string;
          qty: number;
          unit_label: string;
          expected_at: string | null;
          received_at: string | null;
          received_by: string | null;
          notes: string | null;
          position: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          dossier_id: string;
          type: Database["public"]["Enums"]["dossier_item_type"];
          label: string;
          ref?: string | null;
          supplier_id?: string | null;
          couturiere_id?: string | null;
          status?: Database["public"]["Enums"]["dossier_item_status"];
          qr_code: string;
          qty?: number;
          unit_label?: string;
          expected_at?: string | null;
          received_at?: string | null;
          received_by?: string | null;
          notes?: string | null;
          position?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          dossier_id?: string;
          type?: Database["public"]["Enums"]["dossier_item_type"];
          label?: string;
          ref?: string | null;
          supplier_id?: string | null;
          couturiere_id?: string | null;
          status?: Database["public"]["Enums"]["dossier_item_status"];
          qr_code?: string;
          qty?: number;
          unit_label?: string;
          expected_at?: string | null;
          received_at?: string | null;
          received_by?: string | null;
          notes?: string | null;
          position?: number;
          created_at?: string;
        };
        Relationships: [];
      };
      dossiers: {
        Row: {
          id: string;
          number: string;
          devis_id: string | null;
          client_id: string;
          status: Database["public"]["Enums"]["dossier_status"];
          total_ttc: number;
          acompte_paid: boolean;
          acompte_paid_at: string | null;
          solde_paid: boolean;
          solde_paid_at: string | null;
          scheduled_pose_at: string | null;
          poseur_id: string | null;
          workshop_notes: string | null;
          created_at: string;
          updated_at: string;
          atelier_id: string | null;
          atelier_sent_at: string | null;
          store_id: string | null;
          attente_matiere_at: string | null;
          confection_started_at: string | null;
          pret_pose_at: string | null;
          cloture_at: string | null;
          atelier_deadline_at: string | null;
        };
        Insert: {
          id?: string;
          number: string;
          devis_id?: string | null;
          client_id: string;
          status?: Database["public"]["Enums"]["dossier_status"];
          total_ttc: number;
          acompte_paid?: boolean;
          acompte_paid_at?: string | null;
          solde_paid?: boolean;
          solde_paid_at?: string | null;
          scheduled_pose_at?: string | null;
          poseur_id?: string | null;
          workshop_notes?: string | null;
          created_at?: string;
          updated_at?: string;
          atelier_id?: string | null;
          atelier_sent_at?: string | null;
          store_id?: string | null;
          attente_matiere_at?: string | null;
          confection_started_at?: string | null;
          pret_pose_at?: string | null;
          cloture_at?: string | null;
          atelier_deadline_at?: string | null;
        };
        Update: {
          id?: string;
          number?: string;
          devis_id?: string | null;
          client_id?: string;
          status?: Database["public"]["Enums"]["dossier_status"];
          total_ttc?: number;
          acompte_paid?: boolean;
          acompte_paid_at?: string | null;
          solde_paid?: boolean;
          solde_paid_at?: string | null;
          scheduled_pose_at?: string | null;
          poseur_id?: string | null;
          workshop_notes?: string | null;
          created_at?: string;
          updated_at?: string;
          atelier_id?: string | null;
          atelier_sent_at?: string | null;
          store_id?: string | null;
          attente_matiere_at?: string | null;
          confection_started_at?: string | null;
          pret_pose_at?: string | null;
          cloture_at?: string | null;
          atelier_deadline_at?: string | null;
        };
        Relationships: [];
      };
      dossier_notes: {
        Row: {
          id: string;
          dossier_id: string;
          author_id: string | null;
          body: string;
          kind: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          dossier_id: string;
          author_id?: string | null;
          body: string;
          kind?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          dossier_id?: string;
          author_id?: string | null;
          body?: string;
          kind?: string;
          created_at?: string;
        };
        Relationships: [];
      };
      email_log: {
        Row: {
          id: string;
          template_key: string | null;
          client_id: string | null;
          to_email: string;
          subject: string;
          body_html: string;
          brevo_message_id: string | null;
          status: string;
          error: string | null;
          sent_at: string | null;
          delivered_at: string | null;
          created_at: string;
          event_key: string | null;
          trigger_source: string | null;
        };
        Insert: {
          id?: string;
          template_key?: string | null;
          client_id?: string | null;
          to_email: string;
          subject: string;
          body_html: string;
          brevo_message_id?: string | null;
          status?: string;
          error?: string | null;
          sent_at?: string | null;
          delivered_at?: string | null;
          created_at?: string;
          event_key?: string | null;
          trigger_source?: string | null;
        };
        Update: {
          id?: string;
          template_key?: string | null;
          client_id?: string | null;
          to_email?: string;
          subject?: string;
          body_html?: string;
          brevo_message_id?: string | null;
          status?: string;
          error?: string | null;
          sent_at?: string | null;
          delivered_at?: string | null;
          created_at?: string;
          event_key?: string | null;
          trigger_source?: string | null;
        };
        Relationships: [];
      };
      email_templates: {
        Row: {
          id: string;
          key: string;
          label: string;
          subject: string;
          html_body: string;
          text_body: string | null;
          sender_email: string | null;
          sender_name: string | null;
          trigger_description: string | null;
          active: boolean;
          updated_at: string;
        };
        Insert: {
          id?: string;
          key: string;
          label: string;
          subject: string;
          html_body: string;
          text_body?: string | null;
          sender_email?: string | null;
          sender_name?: string | null;
          trigger_description?: string | null;
          active?: boolean;
          updated_at?: string;
        };
        Update: {
          id?: string;
          key?: string;
          label?: string;
          subject?: string;
          html_body?: string;
          text_body?: string | null;
          sender_email?: string | null;
          sender_name?: string | null;
          trigger_description?: string | null;
          active?: boolean;
          updated_at?: string;
        };
        Relationships: [];
      };
      event_alerts: {
        Row: {
          id: string;
          event_key: string;
          label: string;
          active: boolean;
          send_sms: boolean;
          send_email: boolean;
          recipient_phones: string[];
          recipient_emails: string[];
          sms_template_key: string | null;
          email_template_key: string | null;
          sms_body: string | null;
          email_subject: string | null;
          email_html: string | null;
          criteria: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          event_key: string;
          label: string;
          active?: boolean;
          send_sms?: boolean;
          send_email?: boolean;
          recipient_phones?: string[];
          recipient_emails?: string[];
          sms_template_key?: string | null;
          email_template_key?: string | null;
          sms_body?: string | null;
          email_subject?: string | null;
          email_html?: string | null;
          criteria?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          event_key?: string;
          label?: string;
          active?: boolean;
          send_sms?: boolean;
          send_email?: boolean;
          recipient_phones?: string[];
          recipient_emails?: string[];
          sms_template_key?: string | null;
          email_template_key?: string | null;
          sms_body?: string | null;
          email_subject?: string | null;
          email_html?: string | null;
          criteria?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      lm_leads: {
        Row: {
          id: string;
          number: string;
          client_id: string | null;
          region: string;
          product_summary: string;
          status: Database["public"]["Enums"]["lead_status"];
          visio_at: string | null;
          samples_sent_at: string | null;
          devis_id: string | null;
          poseur_id: string | null;
          amount: number | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
          alerts_sent_at: string | null;
        };
        Insert: {
          id?: string;
          number: string;
          client_id?: string | null;
          region: string;
          product_summary: string;
          status?: Database["public"]["Enums"]["lead_status"];
          visio_at?: string | null;
          samples_sent_at?: string | null;
          devis_id?: string | null;
          poseur_id?: string | null;
          amount?: number | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          alerts_sent_at?: string | null;
        };
        Update: {
          id?: string;
          number?: string;
          client_id?: string | null;
          region?: string;
          product_summary?: string;
          status?: Database["public"]["Enums"]["lead_status"];
          visio_at?: string | null;
          samples_sent_at?: string | null;
          devis_id?: string | null;
          poseur_id?: string | null;
          amount?: number | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          alerts_sent_at?: string | null;
        };
        Relationships: [];
      };
      notifications: {
        Row: {
          id: string;
          user_id: string;
          kind: string;
          title: string;
          body: string | null;
          meta: string | null;
          href: string | null;
          read_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          kind: string;
          title: string;
          body?: string | null;
          meta?: string | null;
          href?: string | null;
          read_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          kind?: string;
          title?: string;
          body?: string | null;
          meta?: string | null;
          href?: string | null;
          read_at?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      payments: {
        Row: {
          id: string;
          devis_id: string | null;
          dossier_id: string | null;
          ticket_id: string | null;
          client_id: string | null;
          kind: Database["public"]["Enums"]["payment_kind"];
          method: Database["public"]["Enums"]["payment_method"];
          amount_ttc: number;
          stripe_payment_intent_id: string | null;
          stripe_charge_id: string | null;
          stripe_link_url: string | null;
          cheque_number: string | null;
          reference: string | null;
          notes: string | null;
          paid_at: string;
          recorded_by: string | null;
          pennylane_exported_at: string | null;
          pennylane_invoice_id: string | null;
          pennylane_export_notes: string | null;
          store_id: string | null;
        };
        Insert: {
          id?: string;
          devis_id?: string | null;
          dossier_id?: string | null;
          ticket_id?: string | null;
          client_id?: string | null;
          kind: Database["public"]["Enums"]["payment_kind"];
          method: Database["public"]["Enums"]["payment_method"];
          amount_ttc: number;
          stripe_payment_intent_id?: string | null;
          stripe_charge_id?: string | null;
          stripe_link_url?: string | null;
          cheque_number?: string | null;
          reference?: string | null;
          notes?: string | null;
          paid_at?: string;
          recorded_by?: string | null;
          pennylane_exported_at?: string | null;
          pennylane_invoice_id?: string | null;
          pennylane_export_notes?: string | null;
          store_id?: string | null;
        };
        Update: {
          id?: string;
          devis_id?: string | null;
          dossier_id?: string | null;
          ticket_id?: string | null;
          client_id?: string | null;
          kind?: Database["public"]["Enums"]["payment_kind"];
          method?: Database["public"]["Enums"]["payment_method"];
          amount_ttc?: number;
          stripe_payment_intent_id?: string | null;
          stripe_charge_id?: string | null;
          stripe_link_url?: string | null;
          cheque_number?: string | null;
          reference?: string | null;
          notes?: string | null;
          paid_at?: string;
          recorded_by?: string | null;
          pennylane_exported_at?: string | null;
          pennylane_invoice_id?: string | null;
          pennylane_export_notes?: string | null;
          store_id?: string | null;
        };
        Relationships: [];
      };
      poses: {
        Row: {
          id: string;
          dossier_id: string;
          status: Database["public"]["Enums"]["pose_status"];
          scheduled_at: string | null;
          duration_minutes: number;
          poseur_id: string | null;
          address: string | null;
          notes: string | null;
          completed_at: string | null;
          completion_photo_url: string | null;
          completion_signature_url: string | null;
          client_confirmed: boolean;
          client_confirmed_at: string | null;
          satisfaction_sent: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          dossier_id: string;
          status?: Database["public"]["Enums"]["pose_status"];
          scheduled_at?: string | null;
          duration_minutes?: number;
          poseur_id?: string | null;
          address?: string | null;
          notes?: string | null;
          completed_at?: string | null;
          completion_photo_url?: string | null;
          completion_signature_url?: string | null;
          client_confirmed?: boolean;
          client_confirmed_at?: string | null;
          satisfaction_sent?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          dossier_id?: string;
          status?: Database["public"]["Enums"]["pose_status"];
          scheduled_at?: string | null;
          duration_minutes?: number;
          poseur_id?: string | null;
          address?: string | null;
          notes?: string | null;
          completed_at?: string | null;
          completion_photo_url?: string | null;
          completion_signature_url?: string | null;
          client_confirmed?: boolean;
          client_confirmed_at?: string | null;
          satisfaction_sent?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      poseurs: {
        Row: {
          id: string;
          profile_id: string | null;
          name: string;
          phone: string | null;
          email: string | null;
          zone: string | null;
          internal: boolean;
          active: boolean;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          profile_id?: string | null;
          name: string;
          phone?: string | null;
          email?: string | null;
          zone?: string | null;
          internal?: boolean;
          active?: boolean;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          profile_id?: string | null;
          name?: string;
          phone?: string | null;
          email?: string | null;
          zone?: string | null;
          internal?: boolean;
          active?: boolean;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      profiles: {
        Row: {
          id: string;
          email: string;
          full_name: string;
          role: Database["public"]["Enums"]["user_role"];
          phone: string | null;
          avatar_initial: string | null;
          active: boolean;
          last_seen_at: string | null;
          created_at: string;
          updated_at: string;
          store_id: string | null;
        };
        Insert: {
          id: string;
          email: string;
          full_name: string;
          role?: Database["public"]["Enums"]["user_role"];
          phone?: string | null;
          avatar_initial?: string | null;
          active?: boolean;
          last_seen_at?: string | null;
          created_at?: string;
          updated_at?: string;
          store_id?: string | null;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string;
          role?: Database["public"]["Enums"]["user_role"];
          phone?: string | null;
          avatar_initial?: string | null;
          active?: boolean;
          last_seen_at?: string | null;
          created_at?: string;
          updated_at?: string;
          store_id?: string | null;
        };
        Relationships: [];
      };
      sms_log: {
        Row: {
          id: string;
          template_key: string | null;
          client_id: string | null;
          to_phone: string;
          body: string;
          brevo_message_id: string | null;
          status: string;
          error: string | null;
          sent_at: string | null;
          delivered_at: string | null;
          created_at: string;
          event_key: string | null;
          trigger_source: string | null;
        };
        Insert: {
          id?: string;
          template_key?: string | null;
          client_id?: string | null;
          to_phone: string;
          body: string;
          brevo_message_id?: string | null;
          status?: string;
          error?: string | null;
          sent_at?: string | null;
          delivered_at?: string | null;
          created_at?: string;
          event_key?: string | null;
          trigger_source?: string | null;
        };
        Update: {
          id?: string;
          template_key?: string | null;
          client_id?: string | null;
          to_phone?: string;
          body?: string;
          brevo_message_id?: string | null;
          status?: string;
          error?: string | null;
          sent_at?: string | null;
          delivered_at?: string | null;
          created_at?: string;
          event_key?: string | null;
          trigger_source?: string | null;
        };
        Relationships: [];
      };
      sms_templates: {
        Row: {
          id: string;
          key: string;
          label: string;
          body: string;
          trigger_description: string | null;
          active: boolean;
          updated_at: string;
          sender: string | null;
        };
        Insert: {
          id?: string;
          key: string;
          label: string;
          body: string;
          trigger_description?: string | null;
          active?: boolean;
          updated_at?: string;
          sender?: string | null;
        };
        Update: {
          id?: string;
          key?: string;
          label?: string;
          body?: string;
          trigger_description?: string | null;
          active?: boolean;
          updated_at?: string;
          sender?: string | null;
        };
        Relationships: [];
      };
      sources: {
        Row: {
          id: string;
          key: string;
          label: string;
          color: string;
          active: boolean;
          position: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          key: string;
          label: string;
          color?: string;
          active?: boolean;
          position?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          key?: string;
          label?: string;
          color?: string;
          active?: boolean;
          position?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      stores: {
        Row: {
          id: string;
          slug: string;
          name: string;
          short_name: string | null;
          address: string | null;
          city: string | null;
          postal_code: string | null;
          phone: string | null;
          email: string | null;
          color: string;
          active: boolean;
          position: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          slug: string;
          name: string;
          short_name?: string | null;
          address?: string | null;
          city?: string | null;
          postal_code?: string | null;
          phone?: string | null;
          email?: string | null;
          color?: string;
          active?: boolean;
          position?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          slug?: string;
          name?: string;
          short_name?: string | null;
          address?: string | null;
          city?: string | null;
          postal_code?: string | null;
          phone?: string | null;
          email?: string | null;
          color?: string;
          active?: boolean;
          position?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      suppliers: {
        Row: {
          id: string;
          name: string;
          type: Database["public"]["Enums"]["supplier_type"];
          country: string;
          language: Database["public"]["Enums"]["lang"];
          contact_email: string | null;
          contact_phone: string | null;
          franco_ht: number;
          notes: string | null;
          portal_url: string | null;
          active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          type: Database["public"]["Enums"]["supplier_type"];
          country: string;
          language?: Database["public"]["Enums"]["lang"];
          contact_email?: string | null;
          contact_phone?: string | null;
          franco_ht?: number;
          notes?: string | null;
          portal_url?: string | null;
          active?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          type?: Database["public"]["Enums"]["supplier_type"];
          country?: string;
          language?: Database["public"]["Enums"]["lang"];
          contact_email?: string | null;
          contact_phone?: string | null;
          franco_ht?: number;
          notes?: string | null;
          portal_url?: string | null;
          active?: boolean;
          created_at?: string;
        };
        Relationships: [];
      };
      test_runs: {
        Row: {
          id: string;
          started_at: string;
          ended_at: string | null;
          started_by: string | null;
          mode: string;
          status: string;
          client_id: string | null;
          devis_id: string | null;
          dossier_id: string | null;
          pose_id: string | null;
          client_label: string | null;
          notes: string | null;
          steps: Json;
          steps_total: number;
          steps_done: number;
          steps_error: number;
        };
        Insert: {
          id?: string;
          started_at?: string;
          ended_at?: string | null;
          started_by?: string | null;
          mode?: string;
          status?: string;
          client_id?: string | null;
          devis_id?: string | null;
          dossier_id?: string | null;
          pose_id?: string | null;
          client_label?: string | null;
          notes?: string | null;
          steps?: Json;
          steps_total?: number;
          steps_done?: number;
          steps_error?: number;
        };
        Update: {
          id?: string;
          started_at?: string;
          ended_at?: string | null;
          started_by?: string | null;
          mode?: string;
          status?: string;
          client_id?: string | null;
          devis_id?: string | null;
          dossier_id?: string | null;
          pose_id?: string | null;
          client_label?: string | null;
          notes?: string | null;
          steps?: Json;
          steps_total?: number;
          steps_done?: number;
          steps_error?: number;
        };
        Relationships: [];
      };
    };
    Views: {};
    Functions: {};
    Enums: {
      atmolead_execution_status: "running" | "success" | "failed" | "partial";
      atmolead_job_status: "pending" | "running" | "done" | "failed" | "cancelled";
      atmolead_trigger: "cron" | "manual" | "startup";
      bc_status: "brouillon" | "envoye" | "confirme" | "expedie" | "recu" | "probleme";
      channel: "magasin" | "leroy_merlin" | "ecommerce" | "decoratrice" | "visio";
      devis_status: "brouillon" | "envoye" | "valide" | "acompte_recu" | "refuse" | "expire";
      dossier_item_status: "en_attente" | "commande" | "expedie" | "recu" | "confection" | "probleme";
      dossier_item_type: "tissu" | "rail" | "accessoire" | "autre" | "confection";
      dossier_status: "en_cours" | "tout_commande" | "reception_partielle" | "en_confection" | "pret_pose" | "planifie" | "pose" | "commande_validee" | "attente_matiere" | "confection_en_cours" | "pose_a_planifier" | "pose_a_venir" | "cloture" | "sav";
      lang: "FR" | "EN" | "PL" | "UA" | "DE";
      lead_status: "nouveau" | "visio_planifie" | "echantillons" | "devis_envoye" | "valide" | "perdu";
      payment_kind: "acompte" | "solde" | "comptoir" | "remboursement";
      payment_method: "stripe" | "especes" | "cb" | "cheque" | "virement";
      pose_status: "a_planifier" | "planifie" | "confirme" | "pose" | "annule";
      supplier_type: "tissu" | "rail" | "accessoire" | "couture" | "autre";
      user_role: "admin" | "commercial" | "resp_confection" | "couturiere" | "poseur" | "decoratrice" | "consultation_lm" | "resp_magasin";
    };
    CompositeTypes: Record<string, Record<string, unknown>>;
  };
}
